server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.H2Dialect

  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    check-template-location: true
    cache: false

  mvc:
    static-path-pattern: /static/**

  jackson:
    serialization:
      fail-on-empty-beans: false